spring.application.name=project
#################################
#-------------SQL---------------#
#################################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#################################
#---------JWT,EXPIRATION--------#
#################################
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
#################################
#-----------CLOUDINARY----------#
#################################
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#################################
#--------------GHN--------------#
#################################
ghn.token=${GHN_TOKEN}
ghn.shop-id=${GHN_SHOP_ID}
ghn.url=${GHN_URL}
#################################
#--------------VNP--------------#
#################################
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL}
#################################
#-----------MAILSENDER----------#
#################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#################################
#---------OAUTH2-GOOGLE---------#
#################################
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
#################################
#-------------IMG---------------#
#################################
file.upload-dir=uploads/images
spring.data.web.pageable.one-indexed-parameters=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.devtools.restart.exclude=**/security/CustomUserDetail.class
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.orm.jdbc.bind=TRACE
